#!/usr/bin/env python3
"""
PDF Security Audit Report Generator

Generates a professional, stylish PDF report from audit results.
"""

import sys
import json
from pathlib import Path
from datetime import datetime
import fitz  # PyMuPDF
import os

def generate_report(audit_data: dict, output_path: Path) -> None:
    """
    Generate a professional PDF report from audit results.
    
    Args:
        audit_data: Dictionary containing audit results
        output_path: Path where the PDF should be saved
    """
    # Create new PDF document
    doc = fitz.open()  # Create empty PDF
    
    # Page dimensions (A4)
    page_width = 595
    page_height = 842
    margin = 50
    content_width = page_width - (2 * margin)
    
    # Professional color palette with cyber theme
    color_primary = (0.15, 0.25, 0.4)  # Deep navy blue
    color_secondary = (0.3, 0.3, 0.35)  # Dark gray
    color_danger = (0.8, 0.2, 0.2)  # Red
    color_warning = (0.9, 0.6, 0.1)  # Orange
    color_success = (0.2, 0.6, 0.3)  # Green
    color_dark = (0.1, 0.1, 0.15)  # Very dark gray
    color_light = (0.95, 0.95, 0.97)  # Light gray
    color_text = (0.2, 0.2, 0.25)  # Dark text
    color_text_light = (0.5, 0.5, 0.55)  # Light text
    color_bg_alt = (0.98, 0.98, 0.99)  # Very light background
    color_accent = (0.25, 0.45, 0.7)  # Professional blue accent
    # Cyber theme colors (purple/cyan like the app)
    color_cyber_purple = (0.55, 0.36, 0.96)  # Purple #8B5CF6
    color_cyber_cyan = (0.13, 0.83, 0.93)  # Cyan #22D3EE
    color_cyber_dark = (0.1, 0.1, 0.15)  # Dark background
    color_cyber_gradient_start = (0.2, 0.15, 0.35)  # Dark purple
    color_cyber_gradient_end = (0.15, 0.25, 0.4)  # Dark blue
    
    # Get report data
    report = audit_data.get("reports", [{}])[0] if audit_data.get("reports") else {}
    filename = report.get("filename", "Unknown")
    total_pages = report.get("total_pages", 0)
    flagged_pages = report.get("flagged_pages", [])
    security = report.get("security", {})
    risk_score = security.get("risk_score", 0)
    
    # Helper function to add page header/footer
    def add_page_header_footer(page, page_num, is_cover=False):
        if not is_cover:
            # Header bar
            header_height = 35
            header_rect = fitz.Rect(0, 0, page_width, header_height)
            page.draw_rect(header_rect, color=color_cyber_gradient_start, fill=color_cyber_gradient_start, width=0)
            
            # Header accent line
            accent_line = fitz.Rect(0, 0, page_width, 2)
            page.draw_rect(accent_line, color=color_cyber_cyan, fill=color_cyber_cyan, width=0)
            
            # Header text
            header_text_rect = fitz.Rect(margin, 8, page_width - margin, header_height - 8)
            page.insert_textbox(
                header_text_rect,
                "Vault PDF Audit Report",
                fontsize=11,
                color=(0.9, 0.9, 0.95),
                align=0,
                fontname="helv"
            )
            
            # Page number
            page_num_rect = fitz.Rect(margin, 8, page_width - margin, header_height - 8)
            page.insert_textbox(
                page_num_rect,
                f"Page {page_num}",
                fontsize=10,
                color=(0.9, 0.9, 0.95),
                align=2,
                fontname="helv"
            )
        
        # Footer (on all pages except cover)
        if not is_cover:
            footer_height = 30
            footer_rect = fitz.Rect(0, page_height - footer_height, page_width, page_height)
            footer_bg = (0.98, 0.98, 0.99)
            page.draw_rect(footer_rect, color=footer_bg, fill=footer_bg, width=0)
            
            # Footer accent line
            footer_accent = fitz.Rect(0, page_height - footer_height, page_width, page_height - footer_height + 2)
            page.draw_rect(footer_accent, color=color_cyber_cyan, fill=color_cyber_cyan, width=0)
            
            # Footer text
            footer_text = f"Generated by The Vault Security Checker - {datetime.now().strftime('%B %d, %Y')}"
            footer_text_rect = fitz.Rect(margin, page_height - footer_height + 8, page_width - margin, page_height - 8)
            page.insert_textbox(
                footer_text_rect,
                footer_text,
                fontsize=8,
                color=color_text_light,
                align=1,
                fontname="helv"
            )
    
    # Helper function to draw modern section header with cyber theme
    def draw_section_header(page, y_pos, title, header_color=color_primary):
        header_height = 50
        header_rect = fitz.Rect(margin, y_pos, page_width - margin, y_pos + header_height)
        
        # Ensure header background is dark enough for white text visibility
        # If header_color is too light, use a darker version
        bg_brightness = (header_color[0] + header_color[1] + header_color[2]) / 3
        if bg_brightness > 0.5:  # If background is too light, darken it
            # Use a darker version of the color
            header_color = (
                max(0.1, header_color[0] * 0.6),
                max(0.1, header_color[1] * 0.6),
                max(0.1, header_color[2] * 0.6)
            )
        
        # Gradient background effect (darker at top, lighter at bottom)
        header_top = fitz.Rect(margin, y_pos, page_width - margin, y_pos + header_height / 2)
        header_bottom = fitz.Rect(margin, y_pos + header_height / 2, page_width - margin, y_pos + header_height)
        page.draw_rect(header_top, color=header_color, fill=header_color, width=0)
        # Slightly lighter bottom
        lighter_color = (min(1.0, header_color[0] + 0.1), min(1.0, header_color[1] + 0.1), min(1.0, header_color[2] + 0.1))
        page.draw_rect(header_bottom, color=lighter_color, fill=lighter_color, width=0)
        
        # Accent line at top (cyan for cyber theme)
        accent_line = fitz.Rect(margin, y_pos, page_width - margin, y_pos + 3)
        page.draw_rect(accent_line, color=color_cyber_cyan, fill=color_cyber_cyan, width=0)
        
        # Left accent border (purple)
        left_accent = fitz.Rect(margin, y_pos, margin + 4, y_pos + header_height)
        page.draw_rect(left_accent, color=color_cyber_purple, fill=color_cyber_purple, width=0)
        
        # Title text with better spacing and visibility
        title_rect = fitz.Rect(margin + 20, y_pos + 10, page_width - margin - 15, y_pos + header_height - 10)
        # Use white text for visibility on dark backgrounds
        text_color = (1, 1, 1)  # White
        
        # Insert text with error handling
        rc = page.insert_textbox(
            title_rect,
            title,
            fontsize=24,
            color=text_color,
            align=0,
            fontname="helv"
        )
        
        # Fallback if textbox fails - use insert_text
        if rc < 0:
            # Calculate text position
            text_x = margin + 20
            text_y = y_pos + header_height / 2 + 8  # Center vertically
            page.insert_text(
                fitz.Point(text_x, text_y),
                title,
                fontsize=24,
                color=text_color,
                fontname="helv"
            )
        
        return y_pos + header_height + 25
    
    # Helper function to draw modern premium info card
    def draw_info_card(page, y_pos, label, value, status="OK", is_warning=False, details=None):
        # Ensure value is a string
        value_str = str(value) if value is not None else ""
        label_str = str(label) if label is not None else ""
        status_str = str(status) if status is not None else "OK"
        
        card_height = 45 if not details else 45 + (len(details) * 20)
        card_rect = fitz.Rect(margin, y_pos, page_width - margin, y_pos + card_height)
        
        # Card shadow for depth (lighter to avoid black rendering)
        shadow_offset = 2
        shadow_rect = fitz.Rect(margin + shadow_offset, y_pos + shadow_offset, page_width - margin + shadow_offset, y_pos + card_height + shadow_offset)
        shadow_color = (0.85, 0.85, 0.85)  # Light gray instead of dark
        page.draw_rect(shadow_rect, color=shadow_color, fill=shadow_color, width=0)
        
        # Card background with subtle gradient
        bg_color = (0.99, 0.99, 1.0) if not is_warning else (1.0, 0.98, 0.98)
        page.draw_rect(card_rect, color=bg_color, fill=bg_color, width=0)
        
        # Border
        page.draw_rect(card_rect, color=color_light, width=1)
        
        # Left border accent (thicker, more prominent)
        accent_color = color_success if not is_warning else (color_warning if status == "WARN" else color_danger)
        border_rect = fitz.Rect(margin, y_pos, margin + 6, y_pos + card_height)
        page.draw_rect(border_rect, color=accent_color, fill=accent_color, width=0)
        
        # Status badge with background (lighter to avoid black rendering)
        icon_x = margin + 20
        # Make badge wider for longer text like "WARN"
        status_bg_width = 60 if len(status_str) > 3 else 50
        status_bg_height = 20
        status_bg_rect = fitz.Rect(icon_x, y_pos + 10, icon_x + status_bg_width, y_pos + 10 + status_bg_height)
        status_bg_color = (0.95, 0.95, 0.97)  # Very light background instead of dark
        page.draw_rect(status_bg_rect, color=status_bg_color, fill=status_bg_color, width=0)
        # Add border for definition
        page.draw_rect(status_bg_rect, color=accent_color, width=1.5)
        
        # Status badge text - properly centered within the badge rectangle
        # Use smaller font for longer text to ensure it fits
        font_size = 9 if len(status_str) > 3 else 10
        # Calculate approximate text width (more accurate estimate for helvetica)
        # Helvetica: roughly 0.5 * font_size per character for uppercase
        char_width = 0.5 * font_size
        text_width_approx = char_width * len(status_str)
        # Center horizontally: start position = center - half text width
        status_x = icon_x + (status_bg_width / 2) - (text_width_approx / 2)
        status_y = y_pos + 10 + (status_bg_height / 2) + 3  # Center vertically (add 3 for font baseline)
        try:
            page.insert_text(
                fitz.Point(status_x, status_y),
                status_str,
                fontsize=font_size,
                color=accent_color,
                fontname="helv",
                render_mode=0  # Fill text
            )
        except:
            pass  # If insert_text fails, skip status badge text
        
        # Label with error handling - moved further left for better spacing from status badge
        # Add more spacing after the status badge (was 60, now 75 to give more room)
        label_x = icon_x + status_bg_width + 15  # 15px spacing after badge
        label_y = y_pos + 22
        try:
            page.insert_text(
                fitz.Point(label_x, label_y),
                label_str,
                fontsize=13,
                color=color_text,
                fontname="helv"
            )
        except:
            pass  # If insert_text fails, skip label
        
        # Value with error handling - moved further left to align with label
        value_x = icon_x + status_bg_width + 15  # Same x position as label
        value_y = y_pos + 35
        try:
            page.insert_text(
                fitz.Point(value_x, value_y),
                value_str,
                fontsize=11,
                color=color_text_light,
                fontname="helv"
            )
        except:
            pass  # If insert_text fails, skip value
        
        # Details if provided (with better styling and error handling)
        if details:
            detail_y = y_pos + 50
            # Align details with label/value text (same x position)
            detail_start_x = icon_x + status_bg_width + 15
            detail_bg = fitz.Rect(detail_start_x, detail_y - 5, page_width - margin - 15, detail_y + (len(details[:8]) * 18))
            detail_bg_color = (0.97, 0.97, 0.98)
            page.draw_rect(detail_bg, color=detail_bg_color, fill=detail_bg_color, width=0)
            
            for detail in details[:8]:  # Limit to 8 details
                detail_str = f"• {detail}" if detail else ""
                try:
                    page.insert_text(
                        fitz.Point(detail_start_x + 10, detail_y + 12),  # 10px indent for bullet
                        detail_str,
                        fontsize=9,
                        color=color_text_light,
                        fontname="helv"
                    )
                except:
                    pass  # If insert_text fails, skip this detail
                detail_y += 18
        
        return y_pos + card_height + 15
    
    # Helper function to draw premium metric box
    def draw_metric_box(page, x, y, width, height, label, value, color=color_primary):
        box_rect = fitz.Rect(x, y, x + width, y + height)
        
        # Shadow for depth (lighter to avoid black rendering)
        shadow_offset = 3
        shadow_rect = fitz.Rect(x + shadow_offset, y + shadow_offset, x + width + shadow_offset, y + height + shadow_offset)
        shadow_color = (0.9, 0.9, 0.9)  # Light gray instead of dark
        page.draw_rect(shadow_rect, color=shadow_color, fill=shadow_color, width=0)
        
        # Background with subtle gradient
        bg_top = fitz.Rect(x, y, x + width, y + height / 2)
        bg_bottom = fitz.Rect(x, y + height / 2, x + width, y + height)
        page.draw_rect(bg_top, color=(1, 1, 1), fill=(1, 1, 1), width=0)
        page.draw_rect(bg_bottom, color=color_bg_alt, fill=color_bg_alt, width=0)
        
        # Border
        page.draw_rect(box_rect, color=color_light, width=1.5)
        
        # Top accent bar (thicker, more prominent)
        accent_rect = fitz.Rect(x, y, x + width, y + 5)
        page.draw_rect(accent_rect, color=color, fill=color, width=0)
        
        # Left accent stripe (cyber theme)
        left_stripe = fitz.Rect(x, y, x + 3, y + height)
        page.draw_rect(left_stripe, color=color_cyber_purple, fill=color_cyber_purple, width=0)
        
        # Value (large and bold) - ensure text is visible
        value_str = str(value) if value is not None else "0"
        value_rect = fitz.Rect(x + 10, y + 12, x + width - 10, y + height - 30)
        # Use insert_textbox with proper error handling
        rc = page.insert_textbox(
            value_rect,
            value_str,
            fontsize=28,
            color=color,
            align=1,
            fontname="helv"
        )
        # If textbox insertion failed (rc < 0), use insert_text as fallback
        if rc < 0:
            # Calculate center point
            center_x = x + width / 2
            center_y = y + (height - 30) / 2 + 12
            page.insert_text(
                fitz.Point(center_x, center_y),
                value_str,
                fontsize=28,
                color=color,
                fontname="helv"
            )
        
        # Label (styled)
        label_rect = fitz.Rect(x + 10, y + height - 25, x + width - 10, y + height - 8)
        rc = page.insert_textbox(
            label_rect,
            label.upper(),
            fontsize=10,
            color=color_text_light,
            align=1,
            fontname="helv"
        )
        # If textbox insertion failed, use insert_text as fallback
        if rc < 0:
            center_x = x + width / 2
            center_y = y + height - 15
            page.insert_text(
                fitz.Point(center_x, center_y),
                label.upper(),
                fontsize=10,
                color=color_text_light,
                fontname="helv"
            )
    
    # Page 1: Premium Cover Page with Modern Design
    page = doc.new_page(width=page_width, height=page_height)
    
    # Dark gradient background (cyber theme)
    # Create gradient effect with multiple rectangles
    gradient_steps = 20
    for i in range(gradient_steps):
        y_start = (i / gradient_steps) * page_height
        y_end = ((i + 1) / gradient_steps) * page_height
        ratio = i / gradient_steps
        
        # Interpolate between gradient colors
        r = color_cyber_gradient_start[0] + (color_cyber_gradient_end[0] - color_cyber_gradient_start[0]) * ratio
        g = color_cyber_gradient_start[1] + (color_cyber_gradient_end[1] - color_cyber_gradient_start[1]) * ratio
        b = color_cyber_gradient_start[2] + (color_cyber_gradient_end[2] - color_cyber_gradient_start[2]) * ratio
        
        grad_rect = fitz.Rect(0, y_start, page_width, y_end)
        page.draw_rect(grad_rect, color=(r, g, b), fill=(r, g, b), width=0)
    
    # Decorative top accent bar with gradient effect
    top_bar_height = 180
    top_bar = fitz.Rect(0, 0, page_width, top_bar_height)
    # Dark purple-blue gradient
    page.draw_rect(top_bar, color=color_cyber_gradient_start, fill=color_cyber_gradient_start, width=0)
    
    # Accent line at top (cyan)
    accent_line = fitz.Rect(0, 0, page_width, 4)
    page.draw_rect(accent_line, color=color_cyber_cyan, fill=color_cyber_cyan, width=0)
    
    # Removed decorative corner squares and diagonal lines - they were rendering as black
    
    y_pos = 100
    
    # Main title - "Vault PDF Audit Report" with premium styling
    # Replace subtitle text with PDF audit report icon image
    # Find the image file - check context folder relative to script location
    script_dir = Path(__file__).parent
    project_root = script_dir.parent.parent  # Go up from electron/python to project root
    context_dir = project_root / "context"
    image_path = context_dir / "pdf audit report icon.png"
    
    # If not found in context, try alternative locations
    if not image_path.exists():
        # Try in the same directory as the script
        image_path = script_dir / "pdf audit report icon.png"
    if not image_path.exists():
        # Try in electron directory
        image_path = script_dir.parent / "pdf audit report icon.png"
    
    # Insert image if found, otherwise skip
    if image_path.exists():
        try:
            # Get actual image dimensions to maintain aspect ratio
            img = fitz.open(str(image_path))
            pix = img[0].get_pixmap()
            actual_width = pix.width
            actual_height = pix.height
            img.close()
            
            # Calculate display size - make it bigger and maintain aspect ratio
            max_width = 350  # Larger width
            max_height = 110  # Larger height
            
            # Calculate aspect ratio
            aspect_ratio = actual_width / actual_height
            
            # Scale to fit within max dimensions while maintaining aspect ratio
            if aspect_ratio > (max_width / max_height):
                # Image is wider - use max_width
                image_width = max_width
                image_height = max_width / aspect_ratio
            else:
                # Image is taller - use max_height
                image_height = max_height
                image_width = max_height * aspect_ratio
            
            # Calculate image position - centered above main title
            image_x = (page_width - image_width) / 2  # Center horizontally
            image_y = y_pos - 50  # Position above title with more space
            
            # Insert image with proper aspect ratio
            image_rect = fitz.Rect(image_x, image_y, image_x + image_width, image_y + image_height)
            page.insert_image(image_rect, filename=str(image_path))
        except Exception as e:
            # If image insertion fails, fall back to text
            subtitle_rect = fitz.Rect(margin, y_pos - 25, page_width - margin, y_pos)
            page.insert_textbox(
                subtitle_rect,
                "SECURITY ANALYSIS REPORT",
                fontsize=12,
                color=(0.8, 0.8, 0.9),
                align=1,
                fontname="helv"
            )
    else:
        # Fallback to text if image not found
        subtitle_rect = fitz.Rect(margin, y_pos - 25, page_width - margin, y_pos)
        page.insert_textbox(
            subtitle_rect,
            "SECURITY ANALYSIS REPORT",
            fontsize=12,
            color=(0.8, 0.8, 0.9),
            align=1,
            fontname="helv"
        )
    
    # Main title - large and bold
    title_rect = fitz.Rect(margin, y_pos, page_width - margin, y_pos + 65)
    page.insert_textbox(
        title_rect,
        "Vault PDF Audit Report",
        fontsize=42,
        color=(1, 1, 1),
        align=1,
        fontname="helv"
    )
    
    # Decorative underline accent
    underline_y = y_pos + 70
    underline_width = 200
    underline_x = (page_width - underline_width) / 2
    underline_rect = fitz.Rect(underline_x, underline_y, underline_x + underline_width, underline_y + 3)
    page.draw_rect(underline_rect, color=color_cyber_cyan, fill=color_cyber_cyan, width=0)
    
    y_pos += 150
    
    # Premium file info card with glow effect
    card_margin = 60
    card_padding = 30
    card_width = page_width - (2 * card_margin)
    card_height = 140
    card_y = y_pos
    
    # Card shadow (multiple layers for depth - using light colors to avoid black rendering)
    shadow_offset = 4
    for i in range(3):
        shadow_intensity = 0.9 - (i * 0.03)  # Light gray instead of dark
        shadow_color = (shadow_intensity, shadow_intensity, shadow_intensity)
        shadow_rect = fitz.Rect(
            card_margin + shadow_offset + i,
            card_y + shadow_offset + i,
            card_margin + card_width + shadow_offset + i,
            card_y + card_height + shadow_offset + i
        )
        page.draw_rect(shadow_rect, color=shadow_color, fill=shadow_color, width=0)
    
    # Card background (slightly off-white for subtle effect)
    card_bg = (0.98, 0.98, 0.99)
    card_rect = fitz.Rect(card_margin, card_y, card_margin + card_width, card_y + card_height)
    page.draw_rect(card_rect, color=card_bg, fill=card_bg, width=0)
    
    # Card border with gradient effect (purple to cyan)
    border_thickness = 3
    # Left border (purple)
    left_border = fitz.Rect(card_margin, card_y, card_margin + border_thickness, card_y + card_height)
    page.draw_rect(left_border, color=color_cyber_purple, fill=color_cyber_purple, width=0)
    # Right border (cyan)
    right_border = fitz.Rect(card_margin + card_width - border_thickness, card_y, card_margin + card_width, card_y + card_height)
    page.draw_rect(right_border, color=color_cyber_cyan, fill=color_cyber_cyan, width=0)
    
    # Top accent line (semi-transparent effect using lighter color)
    top_accent_color = (color_cyber_purple[0] * 0.5, color_cyber_purple[1] * 0.5, color_cyber_purple[2] * 0.5)
    top_accent_line = fitz.Rect(card_margin, card_y, card_margin + card_width, card_y + 2)
    page.draw_rect(top_accent_line, color=top_accent_color, fill=top_accent_color, width=0)
    
    # Filename - prominent and styled
    filename_y = card_y + card_padding
    filename_label_rect = fitz.Rect(card_margin + card_padding, filename_y, card_margin + card_width - card_padding, filename_y + 20)
    page.insert_textbox(
        filename_label_rect,
        "AUDITED FILE",
        fontsize=9,
        color=color_text_light,
        align=1,
        fontname="helv"
    )
    
    filename_y += 25
    # Truncate filename if too long
    display_filename = filename
    if len(display_filename) > 60:
        display_filename = display_filename[:57] + "..."
    
    filename_rect = fitz.Rect(card_margin + card_padding, filename_y, card_margin + card_width - card_padding, filename_y + 40)
    page.insert_textbox(
        filename_rect,
        display_filename,
        fontsize=22,
        color=color_text,
        align=1,
        fontname="helv"
    )
    
    # Date - elegantly styled
    date_str = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    date_y = filename_y + 50
    date_rect = fitz.Rect(card_margin + card_padding, date_y, card_margin + card_width - card_padding, date_y + 20)
    page.insert_textbox(
        date_rect,
        date_str,
        fontsize=11,
        color=color_text_light,
        align=1,
        fontname="helv"
    )
    
    y_pos = card_y + card_height + 80
    
    # Risk Score Badge - premium design with glow
    if risk_score is not None:
        risk_color = color_danger if risk_score >= 70 else (color_warning if risk_score >= 40 else color_success)
        risk_label = "HIGH RISK" if risk_score >= 70 else ("MEDIUM RISK" if risk_score >= 40 else "LOW RISK")
        
        badge_width = 320
        badge_height = 120
        badge_x = (page_width - badge_width) / 2
        
        # Badge shadow (lighter to avoid black rendering)
        shadow_color = (0.85, 0.85, 0.85)
        shadow_rect = fitz.Rect(badge_x + 5, y_pos + 5, badge_x + badge_width + 5, y_pos + badge_height + 5)
        page.draw_rect(shadow_rect, color=shadow_color, fill=shadow_color, width=0)
        
        badge_rect = fitz.Rect(badge_x, y_pos, badge_x + badge_width, y_pos + badge_height)
        
        # Badge background with gradient effect
        # Top half
        badge_top = fitz.Rect(badge_x, y_pos, badge_x + badge_width, y_pos + badge_height / 2)
        page.draw_rect(badge_top, color=(1, 1, 1), fill=(1, 1, 1), width=0)
        # Bottom half (slightly darker)
        badge_bottom = fitz.Rect(badge_x, y_pos + badge_height / 2, badge_x + badge_width, y_pos + badge_height)
        page.draw_rect(badge_bottom, color=(0.98, 0.98, 0.99), fill=(0.98, 0.98, 0.99), width=0)
        
        # Badge border with accent
        page.draw_rect(badge_rect, color=risk_color, width=4)
        
        # Inner accent border (lighter color for transparency effect)
        inner_border_color = (risk_color[0] * 0.3, risk_color[1] * 0.3, risk_color[2] * 0.3)
        inner_border = fitz.Rect(badge_x + 8, y_pos + 8, badge_x + badge_width - 8, y_pos + badge_height - 8)
        page.draw_rect(inner_border, color=inner_border_color, width=1)
        
        # Score (large and bold)
        score_rect = fitz.Rect(badge_x, y_pos + 10, badge_x + badge_width, y_pos + 70)
        page.insert_textbox(
            score_rect,
            f"{risk_score}",
            fontsize=48,
            color=risk_color,
            align=1,
            fontname="helv"
        )
        
        # "/100" suffix (smaller)
        suffix_rect = fitz.Rect(badge_x, y_pos + 50, badge_x + badge_width, y_pos + 75)
        page.insert_textbox(
            suffix_rect,
            "/100",
            fontsize=20,
            color=color_text_light,
            align=1,
            fontname="helv"
        )
        
        # Label with subtle background (removed - was rendering as black)
        label_y = y_pos + 75
        label_rect = fitz.Rect(badge_x, label_y, badge_x + badge_width, label_y + 35)
        page.insert_textbox(
            label_rect,
            risk_label,
            fontsize=16,
            color=risk_color,
            align=1,
            fontname="helv"
        )
    
    # Bottom decorative accent line
    bottom_line = fitz.Rect(0, page_height - 50, page_width, page_height - 45)
    page.draw_rect(bottom_line, color=color_cyber_cyan, fill=color_cyber_cyan, width=0)
    
    # Removed bottom corner accents - they were rendering as black
    
    # Page 2: Executive Summary
    page = doc.new_page(width=page_width, height=page_height)
    add_page_header_footer(page, 2)
    y_pos = margin + 40  # Account for header
    
    y_pos = draw_section_header(page, y_pos, "Executive Summary", color_primary)
    
    # Add descriptive subtitle
    subtitle_rect = fitz.Rect(margin + 20, y_pos - 15, page_width - margin - 20, y_pos - 5)
    page.insert_textbox(
        subtitle_rect,
        "Overview of key metrics and risk assessment",
        fontsize=11,
        color=color_text_light,
        align=0,
        fontname="helv"
    )
    
    # Key metrics in boxes
    metric_width = (content_width - 20) / 3
    metric_height = 80
    metric_y = y_pos
    
    draw_metric_box(page, margin, metric_y, metric_width, metric_height, "Total Pages", total_pages, color_primary)
    draw_metric_box(page, margin + metric_width + 10, metric_y, metric_width, metric_height, "Flagged Pages", len(flagged_pages), color_danger if flagged_pages else color_success)
    draw_metric_box(page, margin + (metric_width + 10) * 2, metric_y, metric_width, metric_height, "Risk Score", f"{risk_score}/100", 
                   color_danger if risk_score >= 70 else (color_warning if risk_score >= 40 else color_success))
    
    y_pos = metric_y + metric_height + 30
    
    # Risk Score Visualization
    if risk_score is not None:
        # Section title
        title_rect = fitz.Rect(margin, y_pos, page_width - margin, y_pos + 25)
        page.insert_textbox(
            title_rect,
            "Risk Assessment",
            fontsize=14,
            color=color_text,
            align=0,
            fontname="helv"
        )
        y_pos += 30
        
        # Premium progress bar container with shadow
        bar_width = content_width
        bar_height = 40
        bar_rect = fitz.Rect(margin, y_pos, margin + bar_width, y_pos + bar_height)
        
        # Shadow (lighter to avoid black rendering)
        shadow_rect = fitz.Rect(margin + 2, y_pos + 2, margin + bar_width + 2, y_pos + bar_height + 2)
        page.draw_rect(shadow_rect, color=(0.9, 0.9, 0.9), fill=(0.9, 0.9, 0.9), width=0)
        
        # Background
        page.draw_rect(bar_rect, color=color_light, fill=color_light, width=2)
        
        # Progress fill with gradient effect
        fill_width = (risk_score / 100) * bar_width
        fill_color = color_danger if risk_score >= 70 else (color_warning if risk_score >= 40 else color_success)
        fill_rect = fitz.Rect(margin, y_pos, margin + fill_width, y_pos + bar_height)
        page.draw_rect(fill_rect, color=fill_color, fill=fill_color, width=0)
        
        # Inner highlight on fill
        if fill_width > 5:
            highlight_rect = fitz.Rect(margin, y_pos, margin + fill_width, y_pos + 3)
            highlight_color = (min(1.0, fill_color[0] + 0.2), min(1.0, fill_color[1] + 0.2), min(1.0, fill_color[2] + 0.2))
            page.draw_rect(highlight_rect, color=highlight_color, fill=highlight_color, width=0)
        
        # Score text overlay with better visibility
        score_text_rect = fitz.Rect(margin, y_pos, margin + bar_width, y_pos + bar_height)
        text_color = (1, 1, 1) if risk_score >= 50 else color_text
        page.insert_textbox(
            score_text_rect,
            f"{risk_score}%",
            fontsize=20,
            color=text_color,
            align=1,
            fontname="helv"
        )
        
        y_pos += 50
        
        # Risk interpretation
        interpretation = (
            "HIGH RISK - Multiple serious privacy/security issues detected. Immediate review recommended." 
            if risk_score >= 70 else
            "MEDIUM RISK - Several privacy concerns found. Review recommended." 
            if risk_score >= 40 else
            "LOW RISK - Minor issues only. Document appears relatively secure."
        )
        
        interp_rect = fitz.Rect(margin + 20, y_pos, page_width - margin - 20, y_pos + 40)
        page.insert_textbox(
            interp_rect,
            interpretation,
            fontsize=10,
            color=color_text_light,
            align=0,
            fontname="helv"
        )
    
    # Page 3: Overlay Redaction Analysis
    if flagged_pages:
        page = doc.new_page(width=page_width, height=page_height)
        add_page_header_footer(page, 3)
        y_pos = margin + 40  # Account for header
        
        y_pos = draw_section_header(page, y_pos, "Overlay Redaction Analysis", color_danger)
        
        # Add descriptive subtitle
        subtitle_rect = fitz.Rect(margin + 20, y_pos - 15, page_width - margin - 20, y_pos - 5)
        page.insert_textbox(
            subtitle_rect,
            "Analysis of potentially insecure redaction overlays that may reveal hidden content",
            fontsize=11,
            color=color_text_light,
            align=0,
            fontname="helv"
        )
        
        # Summary
        summary_text = f"Found {len(flagged_pages)} page(s) with potential insecure overlay redactions."
        summary_rect = fitz.Rect(margin + 20, y_pos, page_width - margin - 20, y_pos + 25)
        page.insert_textbox(
            summary_rect,
            summary_text,
            fontsize=11,
            color=color_text,
            align=0,
            fontname="helv"
        )
        y_pos += 35
        
        # Modern Table Header with gradient
        col_widths = [70, 100, 100, 120, 100]
        col_x = margin
        headers = ["Page", "Black Rects", "Overlaps", "Confidence", "Status"]
        header_height = 40
        
        # Header shadow (lighter to avoid black rendering)
        header_shadow = fitz.Rect(margin + 2, y_pos + 2, margin + sum(col_widths) + 2, y_pos + header_height + 2)
        page.draw_rect(header_shadow, color=(0.9, 0.9, 0.9), fill=(0.9, 0.9, 0.9), width=0)
        
        for i, header in enumerate(headers):
            cell_rect = fitz.Rect(col_x, y_pos, col_x + col_widths[i], y_pos + header_height)
            # Gradient effect
            cell_top = fitz.Rect(col_x, y_pos, col_x + col_widths[i], y_pos + header_height / 2)
            cell_bottom = fitz.Rect(col_x, y_pos + header_height / 2, col_x + col_widths[i], y_pos + header_height)
            page.draw_rect(cell_top, color=color_danger, fill=color_danger, width=0)
            lighter_danger = (min(1.0, color_danger[0] + 0.1), min(1.0, color_danger[1] + 0.05), min(1.0, color_danger[2] + 0.05))
            page.draw_rect(cell_bottom, color=lighter_danger, fill=lighter_danger, width=0)
            
            # Accent line at top
            accent_line = fitz.Rect(col_x, y_pos, col_x + col_widths[i], y_pos + 2)
            page.draw_rect(accent_line, color=color_cyber_cyan, fill=color_cyber_cyan, width=0)
            
            page.insert_textbox(
                cell_rect,
                header.upper(),
                fontsize=11,
                color=(1, 1, 1),
                align=1,
                fontname="helv"
            )
            col_x += col_widths[i]
        
        y_pos += header_height + 3
        
        # Table Rows with modern styling
        table_page_num = 3
        for idx, flagged in enumerate(flagged_pages[:25]):  # Limit to 25 rows per page
            if y_pos > page_height - 120:  # Account for footer
                table_page_num += 1
                page = doc.new_page(width=page_width, height=page_height)
                add_page_header_footer(page, table_page_num)
                y_pos = margin + 40
                # Redraw header
                col_x = margin
                header_shadow = fitz.Rect(margin + 2, y_pos + 2, margin + sum(col_widths) + 2, y_pos + header_height + 2)
                page.draw_rect(header_shadow, color=(0.9, 0.9, 0.9), fill=(0.9, 0.9, 0.9), width=0)
                for i, header in enumerate(headers):
                    cell_rect = fitz.Rect(col_x, y_pos, col_x + col_widths[i], y_pos + header_height)
                    cell_top = fitz.Rect(col_x, y_pos, col_x + col_widths[i], y_pos + header_height / 2)
                    cell_bottom = fitz.Rect(col_x, y_pos + header_height / 2, col_x + col_widths[i], y_pos + header_height)
                    page.draw_rect(cell_top, color=color_danger, fill=color_danger, width=0)
                    lighter_danger = (min(1.0, color_danger[0] + 0.1), min(1.0, color_danger[1] + 0.05), min(1.0, color_danger[2] + 0.05))
                    page.draw_rect(cell_bottom, color=lighter_danger, fill=lighter_danger, width=0)
                    accent_line = fitz.Rect(col_x, y_pos, col_x + col_widths[i], y_pos + 2)
                    page.draw_rect(accent_line, color=color_cyber_cyan, fill=color_cyber_cyan, width=0)
                    page.insert_textbox(
                        cell_rect,
                        header.upper(),
                        fontsize=11,
                        color=(1, 1, 1),
                        align=1,
                        fontname="helv"
                    )
                    col_x += col_widths[i]
                y_pos += header_height + 3
            
            # Alternate row colors with subtle borders
            row_color = (0.99, 0.99, 1.0) if idx % 2 == 0 else (1, 1, 1)
            row_rect = fitz.Rect(margin, y_pos, margin + sum(col_widths), y_pos + 32)
            page.draw_rect(row_rect, color=row_color, fill=row_color, width=0)
            # Subtle border
            page.draw_rect(row_rect, color=color_light, width=0.5)
            
            col_x = margin
            confidence = flagged.get('confidence_score', 0)
            status = "HIGH" if confidence >= 7 else ("MEDIUM" if confidence >= 4 else "LOW")
            status_color = color_danger if confidence >= 7 else (color_warning if confidence >= 4 else color_success)
            
            row_data = [
                str(flagged.get("page_number", "")),
                str(flagged.get("black_rect_count", "")),
                str(flagged.get("overlap_count", "")),
                f"{confidence}/10",
                status
            ]
            
            for i, data in enumerate(row_data):
                cell_rect = fitz.Rect(col_x, y_pos, col_x + col_widths[i], y_pos + 32)
                if i == 4:  # Status column
                    # Premium status badge with shadow (lighter to avoid black rendering)
                    status_bg = fitz.Rect(col_x + 6, y_pos + 6, col_x + col_widths[i] - 6, y_pos + 26)
                    status_shadow = fitz.Rect(col_x + 7, y_pos + 7, col_x + col_widths[i] - 5, y_pos + 27)
                    page.draw_rect(status_shadow, color=(0.9, 0.9, 0.9), fill=(0.9, 0.9, 0.9), width=0)
                    page.draw_rect(status_bg, color=status_color, fill=status_color, width=0)
                    page.insert_textbox(
                        cell_rect,
                        data,
                        fontsize=10,
                        color=(1, 1, 1),
                        align=1,
                        fontname="helv"
                    )
                else:
                    page.insert_textbox(
                        cell_rect,
                        data,
                        fontsize=11,
                        color=color_text,
                        align=1,
                        fontname="helv"
                    )
                col_x += col_widths[i]
            
            y_pos += 34
        
        if len(flagged_pages) > 25:
            y_pos += 10
            note_rect = fitz.Rect(margin, y_pos, page_width - margin, y_pos + 20)
            page.insert_textbox(
                note_rect,
                f"Note: Showing first 25 of {len(flagged_pages)} flagged pages. Full details available in audit data.",
                fontsize=9,
                color=color_text_light,
                align=0,
                fontname="helv"
            )
    else:
        # No flagged pages - show success message
        page = doc.new_page(width=page_width, height=page_height)
        add_page_header_footer(page, 3)
        y_pos = margin + 40
        
        y_pos = draw_section_header(page, y_pos, "Overlay Redaction Analysis", color_success)
        
        # Add descriptive subtitle
        subtitle_rect = fitz.Rect(margin + 20, y_pos - 15, page_width - margin - 20, y_pos - 5)
        page.insert_textbox(
            subtitle_rect,
            "Analysis of potentially insecure redaction overlays that may reveal hidden content",
            fontsize=11,
            color=color_text_light,
            align=0,
            fontname="helv"
        )
        
        # Premium success card
        success_card_width = 400
        success_card_x = (page_width - success_card_width) / 2
        success_rect = fitz.Rect(success_card_x, y_pos, success_card_x + success_card_width, y_pos + 80)
        
        # Shadow (lighter to avoid black rendering)
        success_shadow = fitz.Rect(success_card_x + 3, y_pos + 3, success_card_x + success_card_width + 3, y_pos + 80 + 3)
        page.draw_rect(success_shadow, color=(0.9, 0.9, 0.9), fill=(0.9, 0.9, 0.9), width=0)
        
        # Background
        page.draw_rect(success_rect, color=(0.95, 1, 0.95), fill=(0.95, 1, 0.95), width=0)
        page.draw_rect(success_rect, color=color_success, width=3)
        
        # Left accent
        left_accent = fitz.Rect(success_card_x, y_pos, success_card_x + 5, y_pos + 80)
        page.draw_rect(left_accent, color=color_success, fill=color_success, width=0)
        
        success_text_rect = fitz.Rect(success_card_x + 20, y_pos + 20, success_card_x + success_card_width - 20, y_pos + 60)
        page.insert_textbox(
            success_text_rect,
            "No insecure overlay redactions detected",
            fontsize=18,
            color=color_success,
            align=1,
            fontname="helv"
        )
    
    # Page 4+: Security & Privacy Findings
    page = doc.new_page(width=page_width, height=page_height)
    add_page_header_footer(page, 4)
    y_pos = margin + 40
    
    # Use a darker color for Security & Privacy Findings header for better visibility
    security_header_color = (0.2, 0.25, 0.35)  # Dark blue-gray instead of light gray
    y_pos = draw_section_header(page, y_pos, "Security & Privacy Findings", security_header_color)
    
    # Add descriptive subtitle
    subtitle_rect = fitz.Rect(margin + 20, y_pos - 15, page_width - margin - 20, y_pos - 5)
    page.insert_textbox(
        subtitle_rect,
        "Comprehensive security and privacy analysis including metadata, hidden content, and document structure",
        fontsize=11,
        color=color_text_light,
        align=0,
        fontname="helv"
    )
    
    # Track page numbers
    current_page_num = 2  # Start at 2 (cover is page 1)
    
    # Helper function to add finding with better formatting
    def add_finding(page, y_pos, label, value, is_warning=False, details=None, status="OK"):
        nonlocal current_page_num
        if y_pos > page_height - 150:  # Account for footer
            current_page_num += 1
            page = doc.new_page(width=page_width, height=page_height)
            add_page_header_footer(page, current_page_num)
            y_pos = margin + 40
        
        return draw_info_card(page, y_pos, label, value, status, is_warning, details), page
    
    # Reorganize to match app display order - show ALL checks in order
    
    # 1. Metadata Present
    metadata_keys = security.get("metadata_keys", [])
    metadata_details = security.get("metadata_details", {})
    has_metadata = security.get("has_metadata", False)
    
    if has_metadata and metadata_keys:
        # Filter out technical PDF properties
        technical_fields = {'format', 'producer', 'pdf_version', 'page_count', 'is_encrypted', 
                           'needs_password', 'permissions', 'is_pdf', 'is_form_pdf', 'encryption'}
        filtered_keys = [k for k in metadata_keys if k.lower() not in technical_fields]
        filtered_count = len(filtered_keys)
        
        details = []
        if metadata_details:
            filtered_metadata = {k: v for k, v in metadata_details.items() 
                                if k.lower() not in technical_fields and v and str(v).strip()}
            security_priority = ['title', 'author', 'subject', 'creator', 'keywords', 'moddate', 'creationdate']
            sorted_items = []
            for priority_key in security_priority:
                if priority_key in filtered_metadata:
                    sorted_items.append((priority_key, filtered_metadata[priority_key]))
            for key, value in filtered_metadata.items():
                if key not in security_priority:
                    sorted_items.append((key, value))
            for key, value in sorted_items[:8]:
                value_str = str(value)
                if len(value_str) > 60:
                    value_str = value_str[:57] + "..."
                details.append(f"{key}: {value_str}")
        elif filtered_keys:
            details = filtered_keys[:8]
        
        if filtered_count > 0:
            y_pos, page = add_finding(
                page, y_pos,
                "Metadata Present",
                f"({filtered_count} key{'s' if filtered_count != 1 else ''})",
                is_warning=True,
                details=details,
                status="WARN"
            )
        else:
            y_pos, page = add_finding(page, y_pos, "Metadata Present", "No metadata detected", is_warning=False, status="OK")
    else:
        y_pos, page = add_finding(page, y_pos, "Metadata Present", "No metadata detected", is_warning=False, status="OK")
    
    # 2. Attachments
    if security.get("has_attachments"):
        count = security.get("attachment_count", 0)
        names = security.get("attachment_names", [])
        details = names[:8] if names else []
        y_pos, page = add_finding(
            page, y_pos,
            "Attachments",
            f"{count} file(s) embedded",
            is_warning=True,
            details=details,
            status="WARN"
        )
    else:
        y_pos, page = add_finding(page, y_pos, "Attachments", "No attachments", is_warning=False, status="OK")
    
    # 3. Annotations
    if security.get("has_annotations"):
        count = security.get("annotation_count", 0)
        types = security.get("annotation_types", [])
        reviewers = security.get("reviewer_names", [])
        details = []
        if types:
            details.append(f"Types: {', '.join(types)}")
        if reviewers:
            details.append(f"Reviewers: {', '.join(reviewers[:5])}")
            if len(reviewers) > 5:
                details.append(f"...and {len(reviewers) - 5} more reviewers")
        y_pos, page = add_finding(
            page, y_pos,
            "Annotations",
            f"{count} annotation(s) found",
            is_warning=True,
            details=details,
            status="WARN"
        )
    else:
        y_pos, page = add_finding(page, y_pos, "Annotations", "No annotations", is_warning=False, status="OK")
    
    # 4. Form Fields
    if security.get("has_forms"):
        count = security.get("form_field_count", 0)
        y_pos, page = add_finding(
            page, y_pos,
            "Form Fields",
            f"{count} field(s) present",
            is_warning=True,
            status="WARN"
        )
    else:
        y_pos, page = add_finding(page, y_pos, "Form Fields", "No form fields", is_warning=False, status="OK")
    
    # 5. Layers
    if security.get("has_layers"):
        count = security.get("layer_count", 0)
        y_pos, page = add_finding(
            page, y_pos,
            "Layers",
            f"{count} layer(s) detected - Hidden layers may contain sensitive content",
            is_warning=True,
            status="WARN"
        )
    else:
        y_pos, page = add_finding(page, y_pos, "Layers", "No layers detected", is_warning=False, status="OK")
    
    # 6. JavaScript
    if security.get("has_javascript"):
        count = security.get("javascript_count", 0) or 1
        y_pos, page = add_finding(
            page, y_pos,
            "JavaScript",
            f"{count} instance(s) - Potential security risk",
            is_warning=True,
            status="WARN"
        )
    else:
        y_pos, page = add_finding(page, y_pos, "JavaScript", "No JavaScript", is_warning=False, status="OK")
    
    # 7. Hidden Text
    if security.get("has_hidden_text"):
        hidden_types = security.get("hidden_text_types", [])
        white_pages = security.get("white_on_white_pages", [])
        offpage_pages = security.get("offpage_text_pages", [])
        details = []
        if white_pages:
            page_list = ', '.join(map(str, white_pages[:15]))
            details.append(f"White-on-white text on pages: {page_list}")
            if len(white_pages) > 15:
                details.append(f"...and {len(white_pages) - 15} more pages")
        if offpage_pages:
            page_list = ', '.join(map(str, offpage_pages[:15]))
            details.append(f"Off-page text on pages: {page_list}")
            if len(offpage_pages) > 15:
                details.append(f"...and {len(offpage_pages) - 15} more pages")
        if hidden_types:
            details.insert(0, f"Types: {', '.join(hidden_types)}")
        
        y_pos, page = add_finding(
            page, y_pos,
            "Hidden Text",
            f"{len(hidden_types)} type(s) detected",
            is_warning=True,
            details=details,
            status="WARN"
        )
    else:
        y_pos, page = add_finding(page, y_pos, "Hidden Text", "No hidden text detected", is_warning=False, status="OK")
    
    # 8. OCR Layer
    if security.get("has_ocr_layer"):
        ocr_pages = security.get("ocr_pages", [])
        is_scanned = security.get("is_scanned", False)
        details = []
        if ocr_pages:
            page_list = ', '.join(map(str, ocr_pages[:15]))
            details.append(f"Pages with OCR: {page_list}")
            if len(ocr_pages) > 15:
                details.append(f"...and {len(ocr_pages) - 15} more pages")
        if is_scanned:
            details.append("Document appears to be scanned")
        y_pos, page = add_finding(
            page, y_pos,
            "OCR Layer",
            "Detected",
            is_warning=True,
            details=details,
            status="WARN"
        )
    else:
        y_pos, page = add_finding(page, y_pos, "OCR Layer", "No OCR layer detected", is_warning=False, status="OK")
    
    # 9. External Links
    if security.get("has_external_links"):
        urls = security.get("external_urls", [])
        details = urls[:8] if urls else []
        y_pos, page = add_finding(
            page, y_pos,
            "External Links",
            f"{len(urls)} URL(s) found",
            is_warning=True,
            details=details,
            status="WARN"
        )
    else:
        y_pos, page = add_finding(page, y_pos, "External Links", "No external links", is_warning=False, status="OK")
    
    # 10. Digital Signatures
    if security.get("has_signatures"):
        count = security.get("signature_count", 0)
        signers = security.get("signer_names", [])
        details = signers[:8] if signers else []
        y_pos, page = add_finding(
            page, y_pos,
            "Digital Signatures",
            f"{count} signature(s) present",
            is_warning=True,
            details=details,
            status="WARN"
        )
    else:
        y_pos, page = add_finding(page, y_pos, "Digital Signatures", "No digital signatures", is_warning=False, status="OK")
    
    # 11. Watermarks
    if security.get("has_watermarks"):
        y_pos, page = add_finding(
            page, y_pos,
            "Watermarks",
            "Potential watermarks detected (may be used for leak tracing)",
            is_warning=True,
            status="WARN"
        )
    else:
        y_pos, page = add_finding(page, y_pos, "Watermarks", "No obvious watermarks", is_warning=False, status="OK")
    
    # 12. Document Actions
    if security.get("has_actions"):
        y_pos, page = add_finding(
            page, y_pos,
            "Document Actions",
            "Auto-execute on open",
            is_warning=True,
            status="WARN"
        )
    else:
        y_pos, page = add_finding(page, y_pos, "Document Actions", "No document actions", is_warning=False, status="OK")
    
    # 13. Thumbnails
    if security.get("has_thumbnails"):
        y_pos, page = add_finding(
            page, y_pos,
            "Thumbnails",
            "Thumbnail images present",
            is_warning=True,
            status="WARN"
        )
    else:
        y_pos, page = add_finding(page, y_pos, "Thumbnails", "No thumbnails", is_warning=False, status="OK")
    
    # 14. Incremental Updates
    if security.get("incremental_updates") or security.get("incremental_updates_suspected"):
        version_count = security.get("version_count", 0) or 1
        y_pos, page = add_finding(
            page, y_pos,
            "Incremental Updates",
            f"Detected (~{version_count} versions) - May contain earlier drafts",
            is_warning=True,
            status="WARN"
        )
    else:
        y_pos, page = add_finding(page, y_pos, "Incremental Updates", "No incremental updates detected", is_warning=False, status="OK")
    
    # Notes section
    notes = security.get("notes", [])
    if notes:
        y_pos += 20
        if y_pos > page_height - 150:
            current_page_num += 1
            page = doc.new_page(width=page_width, height=page_height)
            add_page_header_footer(page, current_page_num)
            y_pos = margin + 40
        
        # Use a darker color for Additional Notes header for better visibility
        notes_header_color = (0.25, 0.3, 0.35)  # Dark gray instead of light gray
        y_pos = draw_section_header(page, y_pos, "Additional Notes", notes_header_color)
        
        for note in notes:
            note_rect = fitz.Rect(margin + 20, y_pos, page_width - margin - 20, y_pos + 25)
            page.insert_textbox(
                note_rect,
                f"- {note}",
                fontsize=10,
                color=color_text,
                align=0,
                fontname="helv"
            )
            y_pos += 28
    
    # Footer is already added by add_page_header_footer function
    
    # Save PDF
    doc.save(str(output_path))
    doc.close()

def main():
    """Main entry point for report generation."""
    if len(sys.argv) < 3:
        print(json.dumps({"error": "Usage: generate_audit_report.py <audit_json> <output_path>"}), file=sys.stderr)
        sys.exit(1)
    
    audit_json_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    
    try:
        # Read audit data
        with open(audit_json_path, 'r', encoding='utf-8') as f:
            audit_data = json.load(f)
        
        # Generate report
        generate_report(audit_data, output_path)
        
        print(json.dumps({"success": True, "output_path": str(output_path)}))
        
    except Exception as e:
        print(json.dumps({"error": str(e), "type": type(e).__name__}), file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == '__main__':
    main()
